services:
  - type: web
    name: viralforge-web
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    autoDeploy: true
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: config.settings
      - key: DJANGO_DEBUG
        value: "False"
      - key: RENDER_SLEEP_FRIENDLY_MODE
        value: "True"
      - key: ENABLE_SCHEDULER
        value: "False"
      - key: DATABASE_URL
        fromDatabase:
          name: viralforge-db
          property: connectionString
databases:
  - name: viralforge-db
    plan: free
