from __future__ import annotations

from datetime import datetime
from math import ceil
import json
import re
from typing import Any

import requests
from django.conf import settings
from django.utils import timezone

from studio.enums import ContentNiche
from studio.models import EventLog, ViralTopic
from .utils import stable_hash, truncate_text


JSON_ONLY_SYSTEM_PROMPT = (
    "You create viral short-form video topics for YouTube Shorts. "
    "Return valid JSON only. No markdown fences, no commentary."
)

VIEWS_FIRST_TOPIC_RULES = (
    "High-priority content angles:\n"
    "- Brainrot / meme-style curiosity hooks.\n"
    "- AI content only when framed around money, secret tools, hidden workflows, or business leverage.\n"
    "- AI ways to earn money.\n"
    "- Money psychology, spending traps, rich-vs-poor behavior, hidden profit tricks.\n"
    "- Business ideas with strong greed, shock, taboo, or status angles.\n"
    "- Dark facts, disturbing truths, internet theories, crime psychology, manipulation, and uncomfortable truths.\n"
    "Style requirements:\n"
    "- Optimize for maximum views, curiosity, and retention over education.\n"
    "- Make every concept feel addictive, scroll-stopping, and slightly dangerous or forbidden.\n"
    "- Favor brainrot-style pacing: easy to understand instantly, high novelty, fast payoff, no slow setup.\n"
    "- Prefer hooks that trigger greed, fear, status, secrecy, or disbelief.\n"
    "- Do not pitch wholesome, inspirational, generic educational, or low-tension topics.\n"
    "- If using AI as the topic, do not make it sound like obvious AI-generated slop.\n"
    "- Do not mention that the video is AI-made, generated by AI, created with AI, or use phrases like 'AI art', 'AI avatar', or 'AI voice'.\n"
    "- Write in a native short-form social style, not polished corporate copy.\n"
)

SIMILARITY_STOP_WORDS = {
    "a",
    "an",
    "and",
    "are",
    "as",
    "at",
    "be",
    "but",
    "by",
    "for",
    "from",
    "how",
    "if",
    "in",
    "into",
    "is",
    "it",
    "of",
    "on",
    "or",
    "that",
    "the",
    "their",
    "this",
    "to",
    "what",
    "why",
    "with",
    "you",
    "your",
}


def _content_provider() -> str:
    return getattr(settings, "CONTENT_GENERATION_PROVIDER", "auto").strip().lower() or "auto"


def _default_model_for_provider(provider: str) -> str:
    configured_model = getattr(settings, "CONTENT_GENERATION_MODEL", "").strip()
    configured_provider = _content_provider()
    if configured_model and configured_provider == provider:
        return configured_model
    if provider == "gemini":
        return "gemini-2.0-flash"
    if provider == "openrouter":
        models = getattr(settings, "OPENROUTER_CONTENT_MODELS", []) or ["x-ai/grok-beta"]
        return models[0]
    if provider == "groq":
        models = getattr(settings, "GROQ_CONTENT_MODELS", []) or ["llama-3.3-70b-versatile"]
        return models[0]
    if provider == "huggingface":
        models = getattr(settings, "HUGGINGFACE_CONTENT_MODELS", []) or ["microsoft/Phi-3-mini-4k-instruct"]
        return models[0]
    return getattr(settings, "OPENAI_CONTENT_MODEL", "chat-latest")


def _provider_api_key(provider: str) -> str:
    key_map = {
        "gemini": getattr(settings, "GEMINI_API_KEY", ""),
        "openai": getattr(settings, "OPENAI_API_KEY", ""),
        "openrouter": getattr(settings, "OPENROUTER_API_KEY", ""),
        "groq": getattr(settings, "GROQ_API_KEY", ""),
        "huggingface": getattr(settings, "HUGGINGFACE_TOKEN", ""),
    }
    return str(key_map.get(provider, "")).strip()


def _provider_enabled(provider: str) -> bool:
    return bool(_provider_api_key(provider))


def _provider_models(provider: str) -> list[str]:
    if provider == "openrouter":
        return list(getattr(settings, "OPENROUTER_CONTENT_MODELS", []) or [_default_model_for_provider(provider)])
    if provider == "groq":
        return list(getattr(settings, "GROQ_CONTENT_MODELS", []) or [_default_model_for_provider(provider)])
    if provider == "huggingface":
        return list(getattr(settings, "HUGGINGFACE_CONTENT_MODELS", []) or [_default_model_for_provider(provider)])
    return [_default_model_for_provider(provider)]


def _provider_base_url(provider: str) -> str:
    if provider == "openrouter":
        return getattr(settings, "OPENROUTER_BASE_URL", "https://openrouter.ai/api/v1").rstrip("/")
    if provider == "groq":
        return getattr(settings, "GROQ_BASE_URL", "https://api.groq.com/openai/v1").rstrip("/")
    if provider == "huggingface":
        return getattr(settings, "HUGGINGFACE_BASE_URL", "https://api-inference.huggingface.co/v1").rstrip("/")
    return getattr(settings, "OPENAI_BASE_URL", "https://api.openai.com/v1").rstrip("/")


def _provider_order() -> list[str]:
    configured = _content_provider()
    default_order = ["gemini", "openrouter", "groq", "openai", "huggingface"]
    if configured == "auto":
        return default_order
    if configured not in default_order:
        raise RuntimeError(f"Unsupported content generation provider: {configured}")
    return [configured, *[provider for provider in default_order if provider != configured]]


def _generation_candidates() -> list[dict[str, str]]:
    candidates: list[dict[str, str]] = []
    seen: set[tuple[str, str]] = set()
    allow_fallbacks = getattr(settings, "CONTENT_GENERATION_ALLOW_FALLBACKS", True)
    configured_provider = _content_provider()
    for provider in _provider_order():
        if not _provider_enabled(provider):
            continue
        for model in _provider_models(provider):
            key = (provider, model)
            if key in seen:
                continue
            seen.add(key)
            candidates.append(
                {
                    "provider": provider,
                    "model": model,
                    "api_key": _provider_api_key(provider),
                    "base_url": _provider_base_url(provider),
                }
            )
        if configured_provider != "auto" and not allow_fallbacks:
            break
    if candidates:
        return candidates
    raise RuntimeError(
        "No live content generation provider is configured. "
        "Set at least one of GEMINI_API_KEY, OPENROUTER_API_KEY, GROQ_API_KEY, OPENAI_API_KEY, or HUGGINGFACE_TOKEN."
    )


def _niche_label(niche: str) -> str:
    try:
        return ContentNiche(niche).label
    except ValueError:
        return niche.replace("-", " ").title()


def _extract_logged_title(log: EventLog) -> str:
    payload_title = (log.payload or {}).get("title", "").strip()
    if payload_title:
        return payload_title
    match = re.search(r"Project '(.+?)' was removed", log.message or "")
    if match:
        return match.group(1).strip()
    return ""


def _recently_used_titles(niche: str | None, limit: int = 40) -> list[str]:
    topic_query = ViralTopic.objects.all()
    if niche:
        topic_query = topic_query.filter(niche=niche)
    current_titles = list(topic_query.values_list("title", flat=True))
    log_titles: list[str] = []
    logs = EventLog.objects.filter(
        event_type__in=["project.created", "project.deleted", "publish.success"]
    ).order_by("-created_at")[:limit]
    for log in logs:
        title = _extract_logged_title(log)
        if title:
            log_titles.append(title)
    seen: list[str] = []
    for title in [*current_titles, *log_titles]:
        if title and title not in seen:
            seen.append(title)
    return seen[:limit]


def _normalize_similarity_text(value: str) -> str:
    return " ".join(re.findall(r"[a-z0-9]+", str(value).lower()))


def _tokenize_similarity_text(value: str) -> set[str]:
    tokens = {
        token
        for token in _normalize_similarity_text(value).split()
        if len(token) >= 3 and token not in SIMILARITY_STOP_WORDS
    }
    return tokens


def _topic_similarity(left: str, right: str) -> float:
    left_tokens = _tokenize_similarity_text(left)
    right_tokens = _tokenize_similarity_text(right)
    if not left_tokens or not right_tokens:
        return 0.0
    overlap = left_tokens & right_tokens
    return len(overlap) / max(min(len(left_tokens), len(right_tokens)), 1)


def _topic_brief(topic: ViralTopic) -> str:
    script_lines = [line.strip() for line in str(topic.script or "").splitlines() if line.strip()]
    preview = " | ".join(script_lines[:3])
    return f"{topic.title.strip()} :: {preview}".strip()


def _recent_topic_briefs(niche: str | None, limit: int = 20) -> list[str]:
    briefs: list[str] = []
    topic_query = ViralTopic.objects.all()
    if niche:
        topic_query = topic_query.filter(niche=niche)
    topics = topic_query.order_by("-created_at")[:limit]
    for topic in topics:
        brief = _topic_brief(topic)
        if brief:
            briefs.append(brief)
    logs = EventLog.objects.filter(
        event_type__in=["project.created", "project.deleted", "publish.success"]
    ).order_by("-created_at")[:limit]
    for log in logs:
        title = _extract_logged_title(log)
        if not title:
            continue
        brief = title.strip()
        if brief and brief not in briefs:
            briefs.append(brief)
    return briefs[:limit]


def estimate_duration_seconds(script: str, scene_plan: list[dict] | None = None) -> int:
    words = max(len(script.split()), 1)
    narration_seconds = ceil(words / 2.2)
    if scene_plan:
        scene_seconds = sum(max(int(scene.get("duration", 0) or 0), 5) for scene in scene_plan)
        narration_seconds = max(narration_seconds, scene_seconds)
    return max(45, min(narration_seconds + 2, 150))


def _scene_duration(text: str, is_intro: bool = False, is_cta: bool = False) -> int:
    word_count = len(text.split())
    duration = max(5, min(14, ceil(word_count / 2.4)))
    if is_intro:
        duration = min(15, duration + 1)
    if is_cta:
        duration = max(4, min(7, duration))
    return duration


def build_scene_plan(intro: str, bullets: list[str], cta: str, visuals: list[str] | None = None) -> list[dict]:
    segments = [intro, *bullets, cta]
    visual_hints = list(visuals or [])
    scene_plan: list[dict] = []
    for index, text in enumerate(segments):
        clean_text = text.strip()
        if not clean_text:
            continue
        visual_hint = visual_hints[index].strip() if index < len(visual_hints) and visual_hints[index] else ""
        scene_plan.append(
            {
                "text": clean_text,
                "duration": _scene_duration(
                    clean_text,
                    is_intro=index == 0,
                    is_cta=index == len(segments) - 1,
                ),
                "visual_hint": visual_hint,
            }
        )
    return scene_plan


def _strip_code_fences(text: str) -> str:
    cleaned = text.strip()
    if cleaned.startswith("```"):
        cleaned = re.sub(r"^```[a-zA-Z0-9_-]*\s*", "", cleaned)
        cleaned = re.sub(r"\s*```$", "", cleaned)
    return cleaned.strip()


def _extract_json_object(text: str) -> dict:
    cleaned = _strip_code_fences(text)
    try:
        return json.loads(cleaned)
    except json.JSONDecodeError:
        match = re.search(r"\{.*\}", cleaned, flags=re.DOTALL)
        if not match:
            raise RuntimeError("Content generator did not return valid JSON.")
        try:
            return json.loads(match.group(0))
        except json.JSONDecodeError as exc:
            raise RuntimeError("Content generator returned malformed JSON.") from exc


def _topic_prompt(niche: str) -> str:
    recent_titles = _recently_used_titles(None, limit=20)
    recent_briefs = _recent_topic_briefs(None, limit=12)
    local_today = timezone.localtime(timezone.now()).strftime("%B %d, %Y")
    prompt = f"Create 1 original { _niche_label(niche) } YouTube Shorts topic for {local_today}.\n\n"
    prompt += "Rules:\n"
    prompt += VIEWS_FIRST_TOPIC_RULES
    prompt += "- Make it feel fresh, clickable, and specific.\n"
    prompt += "- Do not reuse or paraphrase these recent titles:\n"
    prompt += "\n".join(f"  - {title}" for title in recent_titles) if recent_titles else "  - none"
    prompt += "\n"
    prompt += "- Do not reuse the same hook, angle, structure, examples, or payoff from these recent ideas:\n"
    prompt += "\n".join(f"  - {brief}" for brief in recent_briefs) if recent_briefs else "  - none"
    prompt += "\n"
    prompt += "- Return exactly 1 topic.\n"
    prompt += "- Keep intro punchy.\n"
    prompt += "- Return 8 to 12 bullets.\n"
    prompt += "- Each bullet should be a single spoken beat, not a paragraph.\n"
    prompt += "- Use the full available time when helpful and make the script rich enough to run roughly 45 to 150 seconds.\n"
    prompt += "- Make each spoken beat clear on first listen, with fast context and payoff.\n"
    prompt += "- The topic must be meaningfully different from the recent ideas, not just a reworded version.\n"
    prompt += "- Hashtags must be relevant and start with #.\n"
    prompt += "- Visual hints must be concrete search prompts for stock media.\n"
    prompt += "- Avoid generic phrases like 'concept art', 'abstract background', or repeating the title.\n\n"
    prompt += "Return JSON in this format:\n"
    prompt += "{\n"
    prompt += '  "topics": [\n'
    prompt += "    {\n"
    prompt += '      "title": "...",\n'
    prompt += '      "intro": "...",\n'
    prompt += '      "bullets": ["...", "...", "...", "...", "...", "...", "...", "..."],\n'
    prompt += '      "cta": "...",\n'
    prompt += '      "hashtags": ["#...", "#...", "#...", "#...", "#..."],\n'
    prompt += '      "asset_packs": ["..."],\n'
    prompt += '      "visuals": ["...", "...", "...", "...", "...", "...", "...", "...", "...", "..."]\n'
    prompt += "    }\n"
    prompt += "  ]\n"
    prompt += "}\n"
    prompt += "The visuals array must match the spoken segments count exactly: intro + each bullet + cta."
    return prompt


def _gemini_generate(prompt: str) -> dict:
    api_key = _provider_api_key("gemini")
    if not api_key:
        raise RuntimeError("GEMINI_API_KEY is missing.")
    model = _default_model_for_provider("gemini")
    response = requests.post(
        f"https://generativelanguage.googleapis.com/v1beta/models/{model}:generateContent",
        params={"key": api_key},
        json={
            "system_instruction": {"parts": [{"text": JSON_ONLY_SYSTEM_PROMPT}]},
            "contents": [{"parts": [{"text": prompt}]}],
            "generationConfig": {
                "temperature": 0.9,
                "responseMimeType": "application/json",
            },
        },
        timeout=90,
    )
    if not response.ok:
        try:
            error_message = response.json().get("error", {}).get("message", response.text)
        except ValueError:
            error_message = response.text
        raise RuntimeError(f"Gemini topic generation failed: {truncate_text(error_message, 300)}")
    payload = response.json()
    candidates = payload.get("candidates") or []
    if not candidates:
        raise RuntimeError("Gemini returned no content candidates.")
    parts = candidates[0].get("content", {}).get("parts", [])
    text = "".join(part.get("text", "") for part in parts).strip()
    if not text:
        raise RuntimeError("Gemini returned an empty topic response.")
    return _extract_json_object(text)


def _extract_message_text(message: Any) -> str:
    if isinstance(message, str):
        return message.strip()
    if isinstance(message, list):
        parts: list[str] = []
        for item in message:
            if isinstance(item, str):
                parts.append(item)
                continue
            if isinstance(item, dict):
                text = item.get("text")
                if text:
                    parts.append(str(text))
        return "".join(parts).strip()
    if isinstance(message, dict):
        content = message.get("content")
        if content is not None:
            return _extract_message_text(content)
    return ""


def _openai_compatible_generate(prompt: str, *, provider: str, model: str, base_url: str, api_key: str) -> dict:
    if not api_key:
        raise RuntimeError(f"{provider.title()} API key is missing.")
    headers = {
        "Authorization": f"Bearer {api_key}",
        "Content-Type": "application/json",
    }
    if provider == "openrouter":
        headers["HTTP-Referer"] = getattr(settings, "APP_BASE_URL", "http://127.0.0.1:8000")
        headers["X-Title"] = getattr(settings, "CHANNEL_BRAND_NAME", "DarkBrainScroll")
    response = requests.post(
        f"{base_url}/chat/completions",
        headers=headers,
        json={
            "model": model,
            "temperature": 0.9,
            "response_format": {"type": "json_object"},
            "messages": [
                {"role": "system", "content": JSON_ONLY_SYSTEM_PROMPT},
                {"role": "user", "content": prompt},
            ],
        },
        timeout=90,
    )
    if not response.ok:
        try:
            error_message = response.json().get("error", {}).get("message", response.text)
        except ValueError:
            error_message = response.text
        raise RuntimeError(f"{provider.title()} topic generation failed: {truncate_text(error_message, 300)}")
    payload = response.json()
    choices = payload.get("choices") or []
    if not choices:
        raise RuntimeError(f"{provider.title()} returned no choices.")
    message = choices[0].get("message", {})
    text = _extract_message_text(message.get("content"))
    if not text:
        raise RuntimeError(f"{provider.title()} returned empty content.")
    return _extract_json_object(text)


def _generate_topic_payload(niche: str) -> tuple[dict, str, str]:
    prompt = _topic_prompt(niche)
    failures: list[str] = []
    for candidate in _generation_candidates():
        provider = candidate["provider"]
        model = candidate["model"]
        try:
            if provider == "gemini":
                return _gemini_generate(prompt), provider, model
            if provider in {"openai", "openrouter", "groq", "huggingface"}:
                return (
                    _openai_compatible_generate(
                        prompt,
                        provider=provider,
                        model=model,
                        base_url=candidate["base_url"],
                        api_key=candidate["api_key"],
                    ),
                    provider,
                    model,
                )
            failures.append(f"{provider}/{model}: unsupported provider")
        except Exception as exc:
            failures.append(f"{provider}/{model}: {truncate_text(str(exc), 220)}")
    raise RuntimeError("All topic generation providers failed. " + " | ".join(failures))


def _normalize_hashtags(raw_hashtags) -> list[str]:
    hashtags: list[str] = []
    for item in list(raw_hashtags or []):
        tag = str(item).strip()
        if not tag:
            continue
        if not tag.startswith("#"):
            tag = f"#{tag.lstrip('#')}"
        if tag.lower() not in {entry.lower() for entry in hashtags}:
            hashtags.append(tag)
    return hashtags[:8]


def _normalize_bullets(raw_bullets) -> list[str]:
    bullets: list[str] = []
    for item in list(raw_bullets or []):
        text = truncate_text(" ".join(str(item).split()), 220)
        if text:
            bullets.append(text)
    return bullets[:5]


def _normalize_visuals(raw_visuals, expected_count: int) -> list[str]:
    visuals: list[str] = []
    for item in list(raw_visuals or []):
        text = truncate_text(" ".join(str(item).split()), 120)
        if text:
            visuals.append(text)
    if not visuals:
        return [""] * expected_count
    if len(visuals) < expected_count:
        visuals.extend([visuals[-1]] * (expected_count - len(visuals)))
    return visuals[:expected_count]


def _normalize_asset_packs(raw_packs) -> list[str]:
    packs: list[str] = []
    for item in list(raw_packs or []):
        text = truncate_text(" ".join(str(item).split()), 80)
        if text and text.lower() not in {entry.lower() for entry in packs}:
            packs.append(text)
    return packs[:6]


def _validate_topic_payload(payload: dict, niche: str, provider: str, model: str) -> dict:
    topics = payload.get("topics")
    if not isinstance(topics, list) or not topics:
        raise RuntimeError("Content generator returned no topics.")
    first_topic = topics[0]
    if not isinstance(first_topic, dict):
        raise RuntimeError("Content generator returned an invalid topic shape.")

    title = truncate_text(" ".join(str(first_topic.get("title", "")).split()), 110)
    intro = truncate_text(" ".join(str(first_topic.get("intro", "")).split()), 180)
    cta = truncate_text(" ".join(str(first_topic.get("cta", "")).split()), 180)
    bullets = _normalize_bullets(first_topic.get("bullets", []))
    if not title or not intro or not cta or len(bullets) < 4:
        raise RuntimeError("Content generator returned incomplete topic content.")

    visuals = _normalize_visuals(first_topic.get("visuals", []), expected_count=len(bullets) + 2)
    return {
        "title": title,
        "intro": intro,
        "bullets": bullets,
        "cta": cta,
        "hashtags": _normalize_hashtags(first_topic.get("hashtags", [])),
        "asset_packs": _normalize_asset_packs(first_topic.get("asset_packs", [])),
        "visuals": visuals,
        "provider": provider,
        "model": model,
        "generated_at": datetime.utcnow().isoformat(timespec="seconds") + "Z",
        "niche": niche,
    }


def _is_recent_topic_duplicate(niche: str, title: str, intro: str, bullets: list[str]) -> bool:
    candidate_title = _normalize_similarity_text(title)
    if candidate_title and candidate_title in {
        _normalize_similarity_text(item) for item in _recently_used_titles(None, limit=60)
    }:
        return True

    candidate_brief = " ".join([title, intro, *bullets])
    for topic in ViralTopic.objects.order_by("-created_at")[:60]:
        topic_text = " ".join([topic.title, topic.hook, topic.script])
        if _topic_similarity(candidate_brief, topic_text) >= 0.7:
            return True
    return False


def build_ai_topic(niche: str) -> ViralTopic:
    attempts: list[str] = []
    for attempt in range(6):
        raw_payload, provider, model = _generate_topic_payload(niche)
        payload = _validate_topic_payload(raw_payload, niche, provider, model)
        if _is_recent_topic_duplicate(niche, payload["title"], payload["intro"], payload["bullets"]):
            attempts.append(payload["title"])
            continue

        script_lines = [payload["intro"], *payload["bullets"], payload["cta"]]
        script = "\n".join(script_lines)
        scene_plan = build_scene_plan(payload["intro"], payload["bullets"], payload["cta"], visuals=payload["visuals"])
        duration_seconds = estimate_duration_seconds(script, scene_plan)
        content_signature = stable_hash([niche, payload["title"].strip().lower(), " ".join(script.lower().split())])
        return ViralTopic.objects.create(
            niche=niche,
            title=payload["title"],
            hook=payload["intro"],
            script=script,
            scene_plan=scene_plan,
            seo_title=f'{payload["title"]} | {getattr(settings, "CHANNEL_BRAND_NAME", "DarkBrainScroll")}',
            description=script,
            hashtags=payload["hashtags"] or [f"#{niche}", "#shorts", "#viral"],
            source_notes=[
                f"provider:{payload['provider']}",
                f"model:{payload['model']}",
                f"generated-at:{payload['generated_at']}",
                f"estimated-duration:{duration_seconds}",
                f"content-signature:{content_signature}",
                *[f"asset-pack:{pack}" for pack in payload["asset_packs"]],
            ],
            is_trending=False,
        )
    attempted_titles = ", ".join(attempts[:6]) or "none"
    raise RuntimeError(f"Topic generator kept returning repeated ideas for niche '{niche}'. Attempts: {attempted_titles}")
