# Generated by Django 5.2.4 on 2026-05-23 05:11

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChannelProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('platform', models.CharField(choices=[('youtube', 'YouTube Shorts'), ('instagram', 'Instagram Reels'), ('pinterest', 'Pinterest Idea Pins')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('credential_key', models.CharField(blank=True, max_length=120)),
                ('default_hashtags', models.TextField(blank=True)),
                ('rate_limit_per_day', models.PositiveIntegerField(default=2)),
                ('cooldown_minutes', models.PositiveIntegerField(default=60)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ContentTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('niche', models.CharField(choices=[('facts', 'Facts'), ('motivation', 'Motivation'), ('tech', 'Tech Facts'), ('business', 'Business Tips'), ('horror', 'Horror Stories'), ('reddit', 'Reddit Stories'), ('ai', 'AI Facts'), ('money', 'Money Tips'), ('gym', 'Gym Motivation'), ('quotes', 'Quotes'), ('did-you-know', 'Did You Know')], max_length=40)),
                ('hook_template', models.CharField(max_length=240)),
                ('intro_template', models.TextField()),
                ('body_template', models.TextField()),
                ('outro_template', models.TextField(blank=True)),
                ('emoji_style', models.CharField(blank=True, max_length=120)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SchedulerLock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(max_length=80, unique=True)),
                ('locked_until', models.DateTimeField()),
                ('owner', models.CharField(blank=True, max_length=120)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VideoProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('niche', models.CharField(choices=[('facts', 'Facts'), ('motivation', 'Motivation'), ('tech', 'Tech Facts'), ('business', 'Business Tips'), ('horror', 'Horror Stories'), ('reddit', 'Reddit Stories'), ('ai', 'AI Facts'), ('money', 'Money Tips'), ('gym', 'Gym Motivation'), ('quotes', 'Quotes'), ('did-you-know', 'Did You Know')], max_length=40)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('queued', 'Queued'), ('generating', 'Generating'), ('ready', 'Ready'), ('posting', 'Posting'), ('posted', 'Posted'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='draft', max_length=20)),
                ('aspect_ratio', models.CharField(default='9:16', max_length=20)),
                ('target_width', models.PositiveIntegerField(default=1080)),
                ('target_height', models.PositiveIntegerField(default=1920)),
                ('duration_seconds', models.PositiveIntegerField(default=30)),
                ('caption_style', models.JSONField(blank=True, default=dict)),
                ('output_file', models.CharField(blank=True, max_length=255)),
                ('subtitle_file', models.CharField(blank=True, max_length=255)),
                ('voiceover_file', models.CharField(blank=True, max_length=255)),
                ('music_file', models.CharField(blank=True, max_length=255)),
                ('failure_reason', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ViralTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('niche', models.CharField(choices=[('facts', 'Facts'), ('motivation', 'Motivation'), ('tech', 'Tech Facts'), ('business', 'Business Tips'), ('horror', 'Horror Stories'), ('reddit', 'Reddit Stories'), ('ai', 'AI Facts'), ('money', 'Money Tips'), ('gym', 'Gym Motivation'), ('quotes', 'Quotes'), ('did-you-know', 'Did You Know')], max_length=40)),
                ('title', models.CharField(max_length=240)),
                ('hook', models.CharField(max_length=240)),
                ('script', models.TextField()),
                ('scene_plan', models.JSONField(blank=True, default=list)),
                ('seo_title', models.CharField(blank=True, max_length=240)),
                ('description', models.TextField(blank=True)),
                ('hashtags', models.JSONField(blank=True, default=list)),
                ('source_notes', models.JSONField(blank=True, default=list)),
                ('is_trending', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PublishJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('queued', 'Queued'), ('generating', 'Generating'), ('ready', 'Ready'), ('posting', 'Posting'), ('posted', 'Posted'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='queued', max_length=20)),
                ('scheduled_for', models.DateTimeField(default=django.utils.timezone.now)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('remote_post_id', models.CharField(blank=True, max_length=255)),
                ('last_error', models.TextField(blank=True)),
                ('retry_count', models.PositiveIntegerField(default=0)),
                ('order_index', models.PositiveIntegerField(default=0)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='studio.channelprofile')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publish_jobs', to='studio.videoproject')),
            ],
            options={
                'ordering': ['scheduled_for', 'order_index', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='MediaAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset_type', models.CharField(choices=[('image', 'Image'), ('audio', 'Audio'), ('video', 'Video'), ('subtitle', 'Subtitle'), ('music', 'Music')], max_length=20)),
                ('source_url', models.URLField(blank=True)),
                ('local_path', models.CharField(max_length=255)),
                ('credit', models.CharField(blank=True, max_length=240)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='studio.videoproject')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EventLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('level', models.CharField(default='info', max_length=20)),
                ('event_type', models.CharField(max_length=80)),
                ('message', models.TextField()),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('publish_job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='studio.publishjob')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='studio.videoproject')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='videoproject',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='studio.viraltopic'),
        ),
    ]
