# Generated by Django 5.2.4 on 2026-05-23 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoproject',
            name='progress_percent',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='videoproject',
            name='status_message',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
