# Generated by Django 5.2.4 on 2026-05-23 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("studio", "0002_videoproject_progress_percent_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AutomationState",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("key", models.CharField(default="global", max_length=80, unique=True)),
                ("is_enabled", models.BooleanField(default=True)),
                ("auto_upload", models.BooleanField(default=True)),
                ("retry_failures", models.BooleanField(default=True)),
                ("last_started_at", models.DateTimeField(blank=True, null=True)),
                ("last_paused_at", models.DateTimeField(blank=True, null=True)),
                ("last_cycle_at", models.DateTimeField(blank=True, null=True)),
                ("last_error", models.TextField(blank=True)),
            ],
        ),
    ]
