# Generated by Django 5.1.6 on 2026-06-10 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0010_automationstate_selected_niches'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automationstate',
            name='brainrot_mode',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='contenttemplate',
            name='niche',
            field=models.CharField(choices=[('dark-curiosity', 'Dark Curiosity'), ('cars', 'Cars'), ('top-10-cars', 'Top 10 Cars'), ('luxury-cars', 'Luxury Cars'), ('supercars', 'Supercars'), ('car-facts', 'Car Facts'), ('car-news', 'Car Launches & News'), ('celebrity-gossip', 'Celebrity Gossip'), ('facts', 'Facts'), ('motivation', 'Motivation'), ('tech', 'Tech Facts'), ('business', 'Business Tips'), ('horror', 'Horror Stories'), ('reddit', 'Reddit Stories'), ('ai', 'AI Facts'), ('money', 'Money Tips'), ('gym', 'Gym Motivation'), ('quotes', 'Quotes'), ('space', 'Space & Universe'), ('psychology', 'Psychology'), ('crime', 'Crime Stories'), ('mythology', 'Mythology'), ('survival', 'Survival'), ('cute-animals', 'Cute Animals'), ('animals', 'Animal Facts'), ('animal-facts', 'Wild Animal Facts'), ('body', 'Human Body'), ('celebrity', 'Celebrity Stories'), ('celebrity-facts', 'Celebrity Facts'), ('glam', 'Glam & Dance'), ('dance', 'Dance Trends'), ('story', 'Storytelling'), ('meme', 'Meme Content'), ('theory', 'Internet Theories'), ('did-you-know', 'Did You Know')], max_length=40),
        ),
        migrations.AlterField(
            model_name='videoproject',
            name='niche',
            field=models.CharField(choices=[('dark-curiosity', 'Dark Curiosity'), ('cars', 'Cars'), ('top-10-cars', 'Top 10 Cars'), ('luxury-cars', 'Luxury Cars'), ('supercars', 'Supercars'), ('car-facts', 'Car Facts'), ('car-news', 'Car Launches & News'), ('celebrity-gossip', 'Celebrity Gossip'), ('facts', 'Facts'), ('motivation', 'Motivation'), ('tech', 'Tech Facts'), ('business', 'Business Tips'), ('horror', 'Horror Stories'), ('reddit', 'Reddit Stories'), ('ai', 'AI Facts'), ('money', 'Money Tips'), ('gym', 'Gym Motivation'), ('quotes', 'Quotes'), ('space', 'Space & Universe'), ('psychology', 'Psychology'), ('crime', 'Crime Stories'), ('mythology', 'Mythology'), ('survival', 'Survival'), ('cute-animals', 'Cute Animals'), ('animals', 'Animal Facts'), ('animal-facts', 'Wild Animal Facts'), ('body', 'Human Body'), ('celebrity', 'Celebrity Stories'), ('celebrity-facts', 'Celebrity Facts'), ('glam', 'Glam & Dance'), ('dance', 'Dance Trends'), ('story', 'Storytelling'), ('meme', 'Meme Content'), ('theory', 'Internet Theories'), ('did-you-know', 'Did You Know')], max_length=40),
        ),
        migrations.AlterField(
            model_name='viraltopic',
            name='niche',
            field=models.CharField(choices=[('dark-curiosity', 'Dark Curiosity'), ('cars', 'Cars'), ('top-10-cars', 'Top 10 Cars'), ('luxury-cars', 'Luxury Cars'), ('supercars', 'Supercars'), ('car-facts', 'Car Facts'), ('car-news', 'Car Launches & News'), ('celebrity-gossip', 'Celebrity Gossip'), ('facts', 'Facts'), ('motivation', 'Motivation'), ('tech', 'Tech Facts'), ('business', 'Business Tips'), ('horror', 'Horror Stories'), ('reddit', 'Reddit Stories'), ('ai', 'AI Facts'), ('money', 'Money Tips'), ('gym', 'Gym Motivation'), ('quotes', 'Quotes'), ('space', 'Space & Universe'), ('psychology', 'Psychology'), ('crime', 'Crime Stories'), ('mythology', 'Mythology'), ('survival', 'Survival'), ('cute-animals', 'Cute Animals'), ('animals', 'Animal Facts'), ('animal-facts', 'Wild Animal Facts'), ('body', 'Human Body'), ('celebrity', 'Celebrity Stories'), ('celebrity-facts', 'Celebrity Facts'), ('glam', 'Glam & Dance'), ('dance', 'Dance Trends'), ('story', 'Storytelling'), ('meme', 'Meme Content'), ('theory', 'Internet Theories'), ('did-you-know', 'Did You Know')], max_length=40),
        ),
    ]
