# Generated by Django 5.1.6 on 2026-06-14 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("studio", "0011_alter_automationstate_brainrot_mode_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="automationstate",
            name="brainrot_mode",
            field=models.BooleanField(default=False),
        ),
    ]
